### PR TITLE
add rabbitmq:group:consumer command

### PR DESCRIPTION
**Pull request by sashaaro**

### CODE REVIEW

**Comment by theodormanolescu** [comment]
how is this different from [multiple_consumers](https://github.com/eMAGTechLabs/RabbitMqBundle#multiple-consumers) ?

**Comment by sashaaro** [comment]
Multiple Consumers declare common one exchange for multiple queues.

As I meant in readme
```
Consume multiple queues by one worker command for reduce complexity and simplify debugging.
A lot of running php commands can consume significant memory size and 
would be not convinient in development and
testing environment which no need parallel executation.
```

`rabbitmq:group:consumer` command allow "subscribe" to any multiple exhanges for one worker. 
and not depends from exchanges and queues declarations.

It's allow flexable configurate workers for different environments

A lot running php processes  ```./bin/console rabbitmq:consumer``` can consume many resources in dev/test environement.
It would usefull for projects where rabbitmq is primary transport for services communication.
For example one running ```rabbitmq:consumer``` take ~ 40 mb ram. 
if some service have 25 consumers/queues then would take ~ 1gb ram totally.

You can use default group and easely consume combined all queues in synchronous mode for **testing/debuging**
```$ ./bin/console rabbitmq:group:consumer```
Of course **in production** supervisor can running every consumers separatly and parallel with standard ```./bin/console rabbitmq:consumer``` command

**Comment by theodormanolescu** [comment]
Yes, multiple_consumers are locked to a exchange.
From what I see, what you need and what multiple_consummers offers is 90% similar.
Why not update multiple_consumers to support different exchanges, I think it requires less work?
Or with zero development you can have a separate config for dev environment with one exchange and the necessary routing keys.

**Comment by sashaaro** [comment]
Yes, multiple consumers allow define several queues with one exchange. It is make sense. I preferred don't touch it and create new GroupConsumer 
Main idea - it doesn't content queue/exchange declarations, just combine existed exchanges by one consumer worker.

**Comment by sashaaro** [comment]
@theodormanolescu I would like to hear opinions. This feature is unuseful? Probably I clearly explained goals.
By the way currency code design really worse and hard to extends. A lot of duplicate code and unclearly configuration.
I would be prefer rework main components and simplify yaml configs. Maybe in the future I send new pr

**Comment by sashaaro** [comment]
@theodormanolescu ping

**Pull request closed without merging**
